config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'grills#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :grills do
    resources :bookings, only: [:new, :create]
    resources :reviews
  end
  resources :bookings, only: [:show, :destroy, :edit, :update]
  get 'my_grills', to: 'grills#my_grills', as: 'my_grills'
  get 'my_bookings', to: 'bookings#my_bookings', as: 'my_bookings'
  get 'nearby', to: 'grills#nearby', as: 'nearby_grills'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :grill

  def fix_date(date)
    return date.split('-').reverse.join('/')
  end
end

app/models/grill.rb
class Grill < ApplicationRecord
  has_many :bookings
  has_many :photos, dependent: :destroy
  has_many :reviews, dependent: :destroy

  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :grills_type, presence: true
  validates :price, presence: true
  validates :status, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  accepts_nested_attributes_for :photos, reject_if: :all_blank, allow_destroy: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :url, PhotoUploader
  belongs_to :grill
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :grill
  validates :stars, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
  validates :content, presence: true, allow_blank: true
  validates :user, presence: true
  validates :grill, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :grills
  has_many :reviews
  # validates :last_name, presence: true
  # validates :first_name, presence: true
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

   before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :set_grill, only: [:new, :create]

  def index
    @booking = Booking.all
  end

  def show
  end

  def new
    @booking.user = current_user
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.grill = @grill
    if @booking.save
      redirect_to grill_path(@grill)
    else
      render :new
    end
  end

  def destroy
    @booking.destroy
    redirect_to root_url
  end

  def my_bookings
    @bookings = current_user.bookings
    @totals = []
    total = 0
    @bookings.each do |booking|
      total = (booking.grill.price * (booking.check_out - booking.check_in))
      if total.positive?
        @totals << total
      else
        @totals << booking.grill.price
      end
      # raise
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end
# comment
  def booking_params
    params.require(:booking).permit(:check_in, :check_out, :address, :grill_id)
  end

  def set_grill
    @grill = Grill.find(params[:grill_id])
  end
end

app/controllers/grills_controller.rb
class GrillsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_grill, only: [:show, :edit, :update, :destroy]

  def index
    @grills = Grill.all
  end

  def my_grills
    @grills = Grill.where(user: current_user)
  end

  def new
    @grill = Grill.new
  end

  def create
    @grill = Grill.new(grill_params)
    @grill.status = true
    @grill.user = current_user
    if @grill.save
      redirect_to grills_path
    else
      render :new
    end
  end

  def edit
  end

  def show
    @markers = [
      {
        lat: @grill.latitude,
        lng: @grill.longitude,
        # infoWindow: render_to_string(partial: "info_window", locals: { grill: grill }),
        # image_url: helpers.asset_url('pokeball.png')
      }]

    # @grills = Grill.geocoded #returns grills with coordinates

    # @markers = @grills.map do |grill|
    #   {
    #     lat: grill.latitude,
    #     lng: grill.longitude
    #   }
    # end
    @review = Review.new
    @booking = Booking.new
  end

  def update
    if @grill.update(grill_params)
      redirect_to grill_path(@grill)
    else
      render :new
    end
  end

  def destroy
    @grill.destroy
    redirect_to grills_path
  end

  def nearby
    @address = "brazil #{params[:address]}"
    @grill = Grill.new(name: 'tanto faz', description: 'não importa', address: @address, grills_type: 'carvão', price: 1, status: true)
    @grill.geocode
    @coordinates = [@grill.latitude, @grill.longitude]
    # raise
    # mapbox_info = JSON.parse(open("https://api.mapbox.com/geocoding/v5/mapbox.places/#{@address}.json?access_token=pk.eyJ1Ijoidm1mcmNvc3RhIiwiYSI6ImNrMmdmd2d3eDB1a3kzZHAweG45eHdodjgifQ.0VkfpeZaDQ86klNCbtxmxQ").read)
    # @coordinates = mapbox_info['features'][1]['center'].reverse
    @grills = Grill.near(@coordinates, 100).sort_by { |grill| grill.distance_from(@coordinates) }    # raise
  end

  private

  def grill_params
    params.require(:grill).permit(
      :name,
      :description,
      :address,
      :grills_type,
      :price,
      :status,
      photos_attributes: [:id, :url, :url_cache, :grill_id, :_destroy]
    )
  end

  def set_grill
    @grill = Grill.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_grill

  def index
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.grill = Grill.find(params[:grill_id])
    @review.user = current_user
    if @review.save
      redirect_to grill_path(@review.grill)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:stars, :content)
  end

  def set_grill
    @grill = Grill.find(params[:grill_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="bookingModal" tabindex="-1" role="dialog" aria-labelledby="bookingModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="bookingModalLabel">Confirm your booking</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="d-flex justify-content-around">
          <p><strong>Check in:</strong></p>
          <p id='modal-check-in'></p>
        </div>
        <div class="d-flex justify-content-around">
          <p><strong>Check out:</strong></p>
          <p id='modal-check-out'></p>
        </div>
        <div class="d-flex justify-content-around">
          <p><strong>Address:</strong></p>
          <p id='modal-address'></p>
        </div>
        <div class="d-flex justify-content-around">
          <p><strong>Final price:</strong></p>
          <p id='modal-price'></p>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" method='post'>Confirm</button>
      </div>
    </div>
  </div>
</div>

app/views/bookings/my_bookings.html.erb
<div class="bg">
  <div class="container mt-3">
    <div class="row align-items-center">
      <div class="col-sm-12 offset-md-3 col-md-6 text-primary">
        <div class="container">
          <div class="text-primary">
            <div class="bookings mt-3 d-flex flex-column">
              <h1 class="mb-3">Minhas Reservas</h1>
              <% if @bookings.empty? %>
                <h2>Você não possui nenhuma reserva!</h2>
              <% else %>
              <% @bookings.each_with_index do |booking, ind| %>
                  <%= link_to grill_path(booking.grill), class:"btn px-0" do %>

                    <div class="card-product rounded">
                      <% if booking.grill.photos.empty? %>
                        <img src="http://centerbox.com.br/wp-content/uploads/2018/06/210160-churrasco-guia-de-como-temperar-a-carne-como-um-profissional.jpg"/>
                      <% else  %>
                        <%= cl_image_tag booking.grill.photos.first.url %>
                      <% end %>
                      <div class="card-product-infos rounded py-4">
                        <h2><%= booking.grill.name %></h2>
                        <p><strong>Check in:</strong> <%= booking.check_in.strftime("%d / %B / %y") %></p>
                        <p><strong>Check out:</strong> <%= booking.check_out.strftime("%d / %B / %y") %></p>
                        <p><strong>Total price:</strong> R$ <%= @totals[ind] %>,00</p>
                      </div>
                    </div>

                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
  <div class="cards">
    <h2> Reserva </h2>
  <% @booking.each do |booking| %>
      <div class="card-category" >
        <%= link_to  %>
      </div>
    <%end  %>
  </div>
<!-- <a class="btn btn-ghost" href="#">Write a story</a> -->

app/views/grills/_calendar.html.erb
<div class="mt-3 d-flex flex-column">
	<div class="form-wrapper">
    <%= simple_form_for [@grill, @booking] do |f| %>
      <%= f.input :check_in, label_html: { class: 'font-weight-bolder ml-4 text-black-50'},
      as: :string, id: 'check-in',
      required: false,
      input_html: {class: "range_start rounded-pill pl-4 border-0"}, label: 'Data de retirada' %>

      <%= f.input :check_out, label_html: { class: 'font-weight-bolder ml-4 text-black-50'},
      as: :string, id: 'check-out',
      required: false,
      input_html: {class: "range_end rounded-pill pl-4 border-0"}, label: 'Data de devolução' %>

      <%= f.input :address , label_html: { class: 'font-weight-bolder ml-4 text-black-50'},
      as: :string, id: 'address',
      input_html: {class: "rounded-pill pl-4 border-0 mb-5"}, label: 'Endereço' %>

      <%= f.button :submit, "Reservar",
      class: "btn btn-secondary btn-block rounded-pill border-0 font-weight-bolder p-3",
      data: { toggle: 'modal', target: '#bookingModal' },
      id: 'submit-booking' %>
	</div>
</div>
<!-- Modal -->
<div class="modal fade" id="bookingModal" tabindex="-1" role="dialog" aria-labelledby="bookingModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="bookingModalLabel">Confirme as informações</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="d-flex justify-content-around">
          <p><strong>Data de retirada:</strong></p>
          <p id='modal-check-in'></p>
        </div>
        <div class="d-flex justify-content-around">
          <p><strong>Data de devolução:</strong></p>
          <p id='modal-check-out'></p>
        </div>
        <div class="d-flex justify-content-around">
          <p><strong>Endereço:</strong></p>
          <p id='modal-address'></p>
        </div>
        <div class="d-flex justify-content-around">
          <p><strong>Valor total:</strong></p>
          <p id='modal-price'></p>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-mute" data-dismiss="modal">Close</button>
    		<%= f.submit 'Book it', class: "btn btn-secondary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/grills/_photo_fields.html.erb
<div class='nested-fields' >
  <%= f.file_field :url %>

  <%= link_to_remove_association "Remove Photo", f %>
</div>

app/views/grills/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <%= simple_form_for @grill do |f| %>
      <%= f.input :name %>
      <%= f.input :grills_type %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :status %>
      <%= f.submit "Submit", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/grills/index.html.erb
<div class="bg">

  <div class="banner mb-3 rounded" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://previews.123rf.com/images/nd3000/nd30001607/nd3000160700387/61040055-friends-camping-and-having-a-barbecue-in-nature.jpg);">
    <div class="container col-md-6">
      <h1>Precisa de uma churrasqueira para <strong>aquele churras</strong> com os  <strong>amigos?</strong></h1>
      <%= form_tag nearby_grills_path, method: 'get' do %>
        <%= text_field_tag :address, params[:address], class: "form-control string email optional rounded-pill pl-4 border-0 mt-4", placeholder: "Endereço do churrasco" %>
        <%= submit_tag 'Quero minha churrasqueira', class: "btn btn-secondary btn-block rounded-pill mt-2 text-left pl-4" %>
      <% end %>
    </div>
  </div>

  <div class="container">
    <div class="text-primary">
      <div class="cards">
        <% @grills.each do |grill| %>

          <div class="card-trip m-2">
            <%= link_to grill_path(grill), class:"btn" do %>
              <% if grill.photos.empty? %>
                <img src="http://centerbox.com.br/wp-content/uploads/2018/06/210160-churrasco-guia-de-como-temperar-a-carne-como-um-profissional.jpg"/>
              <% else  %>
              <%= cl_image_tag grill.photos.first.url %>
              <% end %>
            <% end %>

            <div class="card-trip-infos">
              <div>
                <h4 class="card-title block-with-text mb-2"><%= grill.name %> </h4>
                <p class="card-text mr-2"><%= grill.address %> </p>
                <h2 class="card-trip-pricing text-secondary mt-2">R$ <%= grill.price %></h2>
              </div>
              <div class="d-flex">
                <% if grill.user.photo.present? %>
                  <%= cl_image_tag grill.user.photo, class:"card-trip-user avatar-bordered" %>
                <% else %>
                  <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered"/>
                <% end %>
              </div>
            </div>
            <div class="d-flex justify-content-center mb-3">
                <%= link_to 'Reservar', grill_path(grill), class: 'btn btn-secondary rounded-pill m-1 btn-block w-75 py-1' %>
              
            </div>
          </div>

        <% end %>        
      </div>
    </div>
  </div>
</div>

app/views/grills/my_grills.html.erb
<div class="bg">
<div class="container">
  <div class="text-primary">
    <div class="cards">
      <% @grills.each do |grill| %>

        <div class="card-trip m-2">
          <%= link_to grill_path(grill), class:"btn" do %>
            <% if grill.photos.empty? %>
              <img src="http://centerbox.com.br/wp-content/uploads/2018/06/210160-churrasco-guia-de-como-temperar-a-carne-como-um-profissional.jpg"/>
            <% else  %>
            <%= cl_image_tag grill.photos.first.url %>
            <% end %>
          <% end %>

          <div class="card-trip-infos">
            <div>
              <h4 class="card-title block-with-text mb-2"><%= grill.name %> </h4>
              <p class="card-text mr-2"><%= grill.address %> </p>
              <h2 class="card-trip-pricing text-secondary mt-2">R$ <%= grill.price %></h2>
            </div>
            <% if grill.user.photo.present? %>
              <%= cl_image_tag grill.user.photo, class:"card-trip-user avatar-bordered" %>
            <% else %>
              <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered"/>
            <% end %>
          </div>
          <div class="d-flex justify-content-center mb-3">
                <%= link_to 'Reservar', grill_path(grill), class: 'btn btn-secondary rounded-pill m-1 btn-block w-75 py-1' %>
              
            </div>
        </div>
      <% end %>        
    </div>
  </div>
</div>
</div>

app/views/grills/nearby.html.erb
<div class="bg">
<div class="container">
  <div class="text-primary">
    <div class="cards">
        <% @grills.each do |grill| %>

          <div class="card-trip m-2">

            <%= link_to grill_path(grill), class:"btn" do %>
              <img src="http://centerbox.com.br/wp-content/uploads/2018/06/210160-churrasco-guia-de-como-temperar-a-carne-como-um-profissional.jpg"/>
            <% end %>
            <div class="card-trip-infos">
              <div>
                <h4 class="card-title"><%= grill.name %> </h4>
                <p class="card-text"><%= grill.address %> </p>
                <p class="card-text"><%= grill.distance_from(@coordinates).round(1) %> km </p>
              </div>
              <h2 class="card-trip-pricing">R$ <%= grill.price %></h2>
              <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered"/>
            </div>
            <div class="d-flex justify-content-center mb-3">
                <%= link_to 'Reservar', grill_path(grill), class: 'btn btn-secondary rounded-pill m-1 btn-block w-75 py-1' %>
              
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>
</div>

app/views/grills/new.html.erb
<div class="bg">
  <div class="container mt-3">
    <div class="row align-items-center">
      <div class="col-sm-12 offset-md-3 col-md-6 text-primary">
        <div class="container">
          <h2 class="pt-5 mb-3 ml-4"><strong>Adicionar churrasqueira</strong></h2>

            <%= simple_form_for(@grill) do |f| %>
              <%= f.error_notification %>
              <%= f.input :name, label_html: { class: 'font-weight-bolder ml-4 text-black-50'},
                          input_html: { class: "rounded-pill pl-4 border-0" }, label: 'Nome da churrasqueira' %>

              <%= f.input :description, label_html: { class: 'font-weight-bolder ml-4 text-black-50'},
                          input_html: { class: "rounded-pill pl-4 border-0" }, label: 'Descrição' %>

              <%= f.input :grills_type, label_html: { class: 'font-weight-bolder ml-4 text-black-50'},
                          input_html: { class: "rounded-pill pl-4 border-0" }, label: 'Tipo' %>

              <%= f.input :address, label_html: { class: 'font-weight-bolder ml-4 text-black-50'},
                          input_html: { class: "rounded-pill pl-4 border-0" }, label: 'Endereço de retirada' %>

              <%= f.input :price, label_html: { class: 'font-weight-bolder ml-4 text-black-50'},
                          input_html: { class: "rounded-pill pl-4 border-0" }, label: 'Preço por dia' %>

              <%= f.simple_fields_for :photos do |photo| %>
                <%=render 'photo_fields', f: photo %>
              <% end %>

              <div class="links">
                <%= link_to_add_association 'Add Photo', f, :photos %>
              </div>

              <%= f.button :submit, class: "btn-secondary btn-block rounded-pill", value: 'Adicionar churrasqueira'  %>

            <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/grills/show.html.erb
<div class="card-category rounded-0" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
	url(https://envato-shoebox-0.imgix.net/bbd1/dd3a-f091-4d67-a3bb-3ff1b6665de1/man_grilling_pork_chops_112308.jpg?auto=compress%2Cformat&fit=max&mark=https%3A%2F%2Felements-assets.envato.com%2Fstatic%2Fwatermark2.png&markalign=center%2Cmiddle&markalpha=18&w=1600&s=bcb3dc991f2ae1685d6c605634a0165b)">
  <div class="container">
    <h1><strong><%= @grill.name %></strong></h1>
  </div>
</div>


<div class="container grill my-3">
		<div class="grill-description">
			<h3><strong><%= @grill.address %></strong> </h3>

			<div class="description d-flex justify-content-between border-bottom mb-2">
				<p class="text-black-50"><%= @grill.description %></p>	
			</div>

			<div class="type d-flex justify-content-between text-black-50">
				<p><strong>Tipo:</strong></p>				<p><%= @grill.grills_type %></p>	
			</div>
			<div class="price d-flex justify-content-between ">
				<p class="text-secondary"><strong>Valor da Diária:</strong></p>
				<div class="d-flex">
					<h3 class="text-secondary mr-2">R$</h3>
					<h3 class="text-secondary" id="price"><%= @grill.price %></h3>
				</div>	
			</div>
		</div>
    
		<div class="offset-md-1 align-items-left">
			<%= render 'calendar' %>
		</div>

	</div>


  <div
  	class="mt-3"
    id="map"
    style="width: 100%;
    height: 400px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV["MAPBOX_API_KEY"] %>">
  </div>
  <div class="container mb-5 mt-3">
	  <div class="review">
	    <%= render 'reviews/index' %>
	  </div>
	</div>

	<div class="container">
	  <div class="review">
	    <%= render 'reviews/modal' %>
	  </div>
	</div>

<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% @grill.photos.each_with_index do |photo, index| %>
    <% if index == 0 %>
    <div class="carousel-item active" >
      <%= cl_image_tag photo.url, class: "d-block w-50" %>
    </div>
    <% else %>
    <div class="carousel-item" >
      <%= cl_image_tag photo.url, class: "d-block w-50" %>
    </div>
    <% end %>
    <% end %>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Quero Churras</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/_form.html.erb
<%= simple_form_for [@grill, @review] do |f| %>
  <div class="d-flex flex-column">
	  <%= f.label :Estrelas %>
	  <%= f.select :stars, [5, 4, 3, 2, 1], class: 'btn' %>
  </div>
  <%= f.input :content, label: 'Comentário' %>
  <%= f.submit 'Add review', class: 'btn btn-secondary' %>
<% end %>

app/views/reviews/_index.html.erb
<!-- <h3>Reviews</h3> -->
<%= link_to 'Add a review!', new_grill_review_path(@grill), data: { toggle: 'modal', target: '#reviewModal' },
class: "btn btn-secondary my-4 px-4 py-2 rounded-pill border-0" %>
<% @grill.reviews.each do |review| %>
	<div class="card p-4 mb-4 border-0 rounded-4">
		<h4>
			<% review.stars.times do %>
				<i class="fas fa-star text-secondary"></i>
			<% end %>
		</h4>
		<p class="text-black-50"><%= review.content %></p>
	</div>
<% end %>

app/views/reviews/index.html.erb
<h3>Reviews</h3>
<%= link_to 'Leave a review!', new_grill_review_path %>
<% @grill.reviews.each do |review| %>
	<div class="card">
		<h4>
			<% review.stars.times do %>
				<i class="fas fa-star"></i>
			<% end %>
		</h4>
		<p><%= review.content %></p>
	</div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
  <%= link_to grills_path, class: "navbar-brand" do %>
    <%= image_tag("logo_azul.svg")%>
    <% end %>

  <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li>  
          <%= link_to "Home", grills_path, class: "nav-link text-secondary mr-2" %>
        </li>
          <%= link_to "Nova churrasqueira", new_grill_path, class: "nav-link text-secondary mr-2" %>
        <li class="nav-item active">
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.present? %>
            <%= cl_image_tag current_user.photo, class:"avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false   %>
          <% else %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Minhas churrasqueiras", my_grills_path, class: "dropdown-item" unless current_user.grills.empty?%>
            <%= link_to "Minhas reservas", my_bookings_path, class: "dropdown-item" %>
            <%= link_to "Editar meu perfil", edit_user_registration_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "text-secondary nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
  </div>
</div>